apiVersion: v1
kind: Service
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
  selector:
    app: todoapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: todoapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todoapp
        tier: frontend
    spec:
      containers:
      - image: upanshusinghal/todoapp:1.0
        name: todoapp
        env:
        - name: MYSQL_HOST
          value: todoapp-mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-root-user
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-database-name
        ports:
        - containerPort: 8080
          name: todoapp
        volumeMounts:
        - name: todoapp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: todoapp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim